site_name: docker-composer
repo_url: https://github.com/rubenhoenle/docker-composer
repo_name: rubenhoenle/docker-composer
theme:
  name: material
  language: de
  favicon: images/favicon.png
  logo: images/docker-composer.svg
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    #- navigation.path
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
